# Generated by Django 3.2.23 on 2024-01-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacegroup',
            name='system',
            field=models.IntegerField(choices=[(1, 'triclinic'), (2, 'monoclinic'), (3, 'orthorhombic'), (4, 'tetragonal'), (5, 'trigonal'), (6, 'hexagonal'), (7, 'cubic'), (8, 'rhombohedral')], verbose_name='lattice system'),
        ),
    ]
