# Generated by Django 3.2.24 on 2025-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatesblock',
            name='is_fractional',
            field=models.BooleanField(default=True, verbose_name='Fractional or Сartesian coordinates'),
        ),
    ]
