# Generated by Django 3.2.23 on 2024-01-18 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='structurecode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refcode', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='spacegroup',
            unique_together={('name', 'hall_name')},
        ),
        migrations.AddField(
            model_name='refinementinfo',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refinement_info', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='refcodepublicationconnection',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refcode', to='structure.publication', verbose_name='Publication'),
        ),
        migrations.AddField(
            model_name='refcodepublicationconnection',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='structure.structurecode', verbose_name='Refcode'),
        ),
        migrations.AddField(
            model_name='reducedcell',
            name='refcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduced_cells', to='structure.structurecode', verbose_name='Refcode'),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='publications', to='structure.Author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='structure.journal', verbose_name='Journal'),
        ),
        migrations.AddField(
            model_name='other',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='normalisedreducedcell',
            name='refcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalised_reduced_cells', to='structure.structurecode', verbose_name='Refcode'),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('name', 'fullname')},
        ),
        migrations.AddField(
            model_name='formula',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='experimentalinfo',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experimental_info', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='elementsset8',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='element_set_8', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='elementsset7',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='element_set_7', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='elementsset6',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='element_set_6', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='elementsset5',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='element_set_5', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='elementsset4',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='element_set_4', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='elementsset3',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='element_set_3', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='elementsset2',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='element_set_2', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='elementsset1',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='element_set_1', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='crystalandstructureinfo',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crystal_and_structure_info', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='coordinatesblock',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='compoundname',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='ciffile',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cif_file', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='cell',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='structure.structurecode'),
        ),
        migrations.AddField(
            model_name='cell',
            name='spacegroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cell', to='structure.spacegroup', verbose_name='space group'),
        ),
        migrations.AddField(
            model_name='calculationprogram',
            name='refcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calc_prog', to='structure.structurecode'),
        ),
        migrations.AlterUniqueTogether(
            name='reducedcell',
            unique_together={('refcode', 'a', 'b', 'c', 'al', 'be', 'ga')},
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together={('journal', 'page', 'volume', 'year', 'doi')},
        ),
        migrations.AlterUniqueTogether(
            name='normalisedreducedcell',
            unique_together={('refcode', 'a', 'b', 'c', 'al', 'be', 'ga')},
        ),
    ]
