# Generated by Django 3.2.23 on 2024-01-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystalandstructureinfo',
            name='sensitivity',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sensitivity'),
        ),
    ]
