# Generated by Django 3.2.24 on 2025-06-03 16:37

from django.db import migrations, models
import django.db.models.deletion
import qc_structure.models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcproperties',
            name='energy',
        ),
        migrations.AddField(
            model_name='qccoordinatesblock',
            name='is_fractional',
            field=models.BooleanField(default=True, verbose_name='Fractional or Сartesian coordinates'),
        ),
        migrations.AddField(
            model_name='qcproperties',
            name='charge',
            field=models.FloatField(default=0, verbose_name='Charge of the system'),
        ),
        migrations.AddField(
            model_name='qcproperties',
            name='dipole_moment',
            field=models.FloatField(blank=True, null=True, verbose_name='Dipole moment, D'),
        ),
        migrations.AddField(
            model_name='qcproperties',
            name='multiplicity',
            field=models.FloatField(blank=True, null=True, verbose_name='Multiplicity'),
        ),
        migrations.AddField(
            model_name='qcstructurecode',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Is structure available for other users'),
        ),
        migrations.CreateModel(
            name='QCInputParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, choices=[('Opt', 'Optimization'), ('SP', 'Single Point')], max_length=5, null=True, verbose_name='Job type (Opt / SP)')),
                ('basis_set', models.CharField(blank=True, max_length=50, null=True, verbose_name='Basis set')),
                ('functional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Functional')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Program version')),
                ('freq', models.BooleanField(blank=True, null=True, verbose_name='Calculate frequencies')),
                ('dispersion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Orca version')),
                ('solvation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Solvation')),
                ('refcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_input', to='qc_structure.qcstructurecode')),
            ],
            options={
                'verbose_name_plural': 'QCInputParameters',
            },
        ),
        migrations.CreateModel(
            name='QCEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_units', models.CharField(default='Eh', max_length=10, verbose_name='Energy units')),
                ('energy', models.FloatField(blank=True, null=True, verbose_name='Final energy')),
                ('zpe', models.FloatField(blank=True, null=True, verbose_name='Zero point energy, Eh')),
                ('enthalpy', models.FloatField(blank=True, null=True, verbose_name='Total enthalpy, Eh')),
                ('entropy', models.FloatField(blank=True, null=True, verbose_name='Final entropy term, Eh')),
                ('gibbs', models.FloatField(blank=True, null=True, verbose_name='Gibbs free energy, Eh')),
                ('homo', models.FloatField(blank=True, null=True, verbose_name='HOMO orbital energy, Eh')),
                ('lumo', models.FloatField(blank=True, null=True, verbose_name='LUMO orbital energy, Eh')),
                ('refcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_energy', to='qc_structure.qcstructurecode')),
            ],
            options={
                'verbose_name_plural': 'QCEnergies',
            },
        ),
        migrations.CreateModel(
            name='OrcaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, upload_to=qc_structure.models.orca_user_directory_path, verbose_name='ORCA .out file')),
                ('refcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orca_file', to='qc_structure.qcstructurecode')),
            ],
        ),
    ]
