# Generated by Django 3.2.24 on 2025-05-29 14:06

from django.db import migrations, models
import django.db.models.deletion
import qc_structure.models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qccoordinatesblock',
            name='is_fractional',
            field=models.BooleanField(default=True, verbose_name='Fractional or Сartesian coordinates'),
        ),
        migrations.AddField(
            model_name='qcproperties',
            name='energy_units',
            field=models.CharField(default='Eh', max_length=10, verbose_name='Energy units'),
        ),
        migrations.AddField(
            model_name='qcproperties',
            name='enthalpy',
            field=models.FloatField(blank=True, null=True, verbose_name='Total enthalpy, Eh'),
        ),
        migrations.AddField(
            model_name='qcproperties',
            name='entropy',
            field=models.FloatField(blank=True, null=True, verbose_name='Final entropy term, Eh'),
        ),
        migrations.AddField(
            model_name='qcproperties',
            name='gibbs',
            field=models.FloatField(blank=True, null=True, verbose_name='Gibbs free energy, Eh'),
        ),
        migrations.AddField(
            model_name='qcproperties',
            name='homo',
            field=models.FloatField(blank=True, null=True, verbose_name='HOMO orbital energy, Eh'),
        ),
        migrations.AddField(
            model_name='qcproperties',
            name='lumo',
            field=models.FloatField(blank=True, null=True, verbose_name='LUMO orbital energy, Eh'),
        ),
        migrations.AddField(
            model_name='qcproperties',
            name='zpe',
            field=models.FloatField(blank=True, null=True, verbose_name='Zero point energy, Eh'),
        ),
        migrations.AlterField(
            model_name='qcproperties',
            name='energy',
            field=models.FloatField(blank=True, null=True, verbose_name='Final energy'),
        ),
        migrations.CreateModel(
            name='OrcaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, upload_to=qc_structure.models.orca_user_directory_path, verbose_name='ORCA .out file')),
                ('refcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orca_file', to='qc_structure.qcstructurecode')),
            ],
        ),
    ]
